/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jrinstall.view;

import br.com.jrinstall.bean.TableMaterial;
import br.com.jrinstall.entity.Cliente;
import br.com.jrinstall.entity.Material;
import br.com.jrinstall.entity.Usuario;
import br.com.jrinstall.helper.MetodosUteis;
import br.com.jrinstall.helper.Validacao;
import br.com.jrinstall.service.MaterialService;
import java.awt.Font;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JDesktopPane;
import javax.swing.UIManager;

/**
 *
 * @author fernando
 */
public class FrmCadastroMaterial extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCadastroMaterial
     */
    private MaterialService service;
    private Material material;

    public JDesktopPane desktopPane;
    private List lista;

    private TableMaterial tableMaterial;
    private Usuario usuarioLogado;
    private Map mapPesquisa;

    public FrmCadastroMaterial() {
        initComponents();

    }

    public FrmCadastroMaterial(JDesktopPane dsk) {
        initComponents();
        MetodosUteis.DesabilitarTextField(this);
        desktopPane = dsk;
        service = new MaterialService();
        jFormattedTextField1.setText("0");
        MetodosUteis.DefineFontTextField(this, "arial",Font.BOLD,16);
    }

    private void preencheDadosDigitados() throws Exception{
        material.setDescricaomaterial(jTextDescricao.getText());
        material.setValorPadrao(0.0);
        if (jFormattedTextField1.getText() != null) {
            material.setValorPadrao(MetodosUteis.ConverteStringToDoule(jFormattedTextField1.getText()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCadastro = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextDescricao = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanelPesquisa = new javax.swing.JPanel();
        jComboTipoPesquisa = new javax.swing.JComboBox();
        jTextPesquisa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();

        setTitle("Cadastro de Material");
        setToolTipText("");

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        jLabel5.setText("Descrição");

        jLabel39.setText("Valor Padrão");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField1MouseClicked(evt);
            }
        });
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", jPanelCadastro);

        jComboTipoPesquisa.addItem("Descricao");
        jComboTipoPesquisa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboTipoPesquisaItemStateChanged(evt);
            }
        });
        jComboTipoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoPesquisaActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(jTable);

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jrinstall/icon/pesquisar-24.png"))); // NOI18N
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPesquisaLayout = new javax.swing.GroupLayout(jPanelPesquisa);
        jPanelPesquisa.setLayout(jPanelPesquisaLayout);
        jPanelPesquisaLayout.setHorizontalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jTextPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPesquisar)
                .addContainerGap())
            .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelPesquisaLayout.setVerticalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jComboTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(11, 11, 11)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Pesquisa", jPanelPesquisa);
        jPanelPesquisa.getAccessibleContext().setAccessibleName("tabPesquisa");

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jrinstall/icon/novo-24.png"))); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jrinstall/icon/salvar-24.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButtonNovo)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonSalvar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonSalvar))
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("tabCadastro");

        getAccessibleContext().setAccessibleName("FrmMaterial");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        MetodosUteis.HabilitarTextField(this);
        MetodosUteis.LimparTextField(this);
        material = new Material();
        jTextDescricao.requestFocus();
        /*
         MetodosUteis.HabilitarTextField(this);
         MetodosUteis.LimparTextField(this);
         cliente = new Cliente();
         cliente.setUsuarioCadastro(usuarioLogado.getUsuario());
         cliente.setDataCadastro(new Date());
         clickNovo();
         */
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        if (validaCampos()) {
            try{
            preencheDadosDigitados();
            service.Save(material);
            clickSalvar();
            MetodosUteis.showMsg("Registro salvo com sucesso!");
            }catch(Exception e){
                MetodosUteis.showMsg("Erro: " + e.getMessage());
            }
            }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void clickNovo() {
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(false);
    }

    private void clickSalvar() {
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(true);
    }
    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jComboTipoPesquisaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboTipoPesquisaItemStateChanged
        // TODO add your handling code here:
        jTextPesquisa.setText(null);
    }//GEN-LAST:event_jComboTipoPesquisaItemStateChanged

    private void jComboTipoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTipoPesquisaActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        material = new Material();
        material = (Material) tableMaterial.getMaterial(jTable.getSelectedRow());
        jTabbedPane1.setSelectedComponent(jPanelCadastro);
        preencheCamposComMaterial(material);
        clickPesquisar();
        MetodosUteis.HabilitarTextField(this);
        jTabbedPane1.setSelectedComponent(jPanelCadastro);
    }//GEN-LAST:event_jTableMouseClicked

    private void clickPesquisar() {
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(true);
    }

    private void preencheCamposComMaterial(Material obj) {
        jTextDescricao.setText(obj.getDescricaomaterial());
        jFormattedTextField1.setText(obj.getValorPadrao().toString());
    }

    private void jTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableMouseEntered

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed

        if (jTextPesquisa.getText().length() == 0) {
            MetodosUteis.showMsg("Informe o Item a pesquisar!");

        } else {
            lista = new ArrayList<Material>();
            String criterio = String.valueOf(jComboTipoPesquisa.getSelectedItem().toString());
            Map mapPesquisa = new HashMap();

            if (criterio.equals("Descricao")) {
                mapPesquisa.put("Descricao", "SELECT m FROM Material m WHERE m.descricaomaterial like '" + jTextPesquisa.getText() + "%'");
            }

            lista = new ArrayList<Material>();
            lista = service.getListByHQL((String) mapPesquisa.get(criterio));
            montaTabela(lista);

        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jFormattedTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField1MouseClicked
jFormattedTextField1.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1MouseClicked

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
       jTextPesquisa.setEditable(true);
    }//GEN-LAST:event_jTabbedPane1FocusGained

     private void montaTabela(List<Material> lista) {
        String colunas[] = new String[]{"Descrição Material", "Valor"};
        ArrayList linhas = new ArrayList<Material>();
        for (Material p : lista) {
            linhas.add(new String[]{p.getDescricaomaterial(), p.getValorPadrao().toString()});
        }
        tableMaterial = new TableMaterial(linhas, colunas, lista);
        jTable.setModel(tableMaterial);
        jTable.getColumnModel().getColumn(0).setHeaderValue("Descrição");
        jTable.getColumnModel().getColumn(0).setPreferredWidth(200);
        jTable.getColumnModel().getColumn(1).setHeaderValue("Valor");
        jTable.getColumnModel().getColumn(1).setPreferredWidth(70);
    }
    private boolean validaCampos() {
        boolean retorno = true;

        StringBuffer str = new StringBuffer();
        str.append("Campos obrigatórios:");

        if (Validacao.campoBranco(jTextDescricao.getText())) {
            retorno = false;
            str.append("\n - Descrição");
            jTextDescricao.requestFocus();
        }

        if (!retorno) {
            MetodosUteis.showMsg(str.toString());
        }
        return retorno;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboTipoPesquisa;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPanel jPanelPesquisa;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextDescricao;
    private javax.swing.JTextField jTextPesquisa;
    // End of variables declaration//GEN-END:variables
}
