/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jrinstall.view;

import br.com.jrinstall.bean.TableCliente;
import br.com.jrinstall.bean.TableItemOS;
import br.com.jrinstall.bean.TableMaterial;
import br.com.jrinstall.bean.TableOrdemServico;
import br.com.jrinstall.bean.TableTelefone;
import br.com.jrinstall.entity.Cliente;
import br.com.jrinstall.entity.ClienteTelefone;
import br.com.jrinstall.entity.Material;
import br.com.jrinstall.entity.OrdemServico;
import br.com.jrinstall.entity.OrdemServicoItem;
import br.com.jrinstall.entity.TipoServico;
import br.com.jrinstall.entity.Usuario;
import br.com.jrinstall.helper.MetodosUteis;
import br.com.jrinstall.service.ClienteService;
import br.com.jrinstall.service.OrdemDeServicoService;
import br.com.jrinstall.service.TipoDeServicoService;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import org.hibernate.HibernateException;
import org.hibernate.tool.hbm2x.StringUtils;

/**
 *
 * @author fernando 02-04-14 Finaliza rpesquisa de OS e preencher os campos com
 * o item selecionado
 */
public class FrmOrdemDeServico extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmOrdemDeServico
     */
    public JDesktopPane desktopPane;
    private OrdemDeServicoService service;
    private OrdemServico ordemServico;
    private OrdemServicoItem ordemItem;
    private List<OrdemServicoItem> listaItens;
    private TableOrdemServico tableOrdemServico;
    private Usuario usuarioLogado;
    private Map mapPesquisa;
    private Map mapTipoServico;
    private List lista;
    private ClienteService clienteService;
    private TableCliente tableCliente;
    private TableTelefone tabelaTelefone;
    private TableMaterial tableMaterial;
    private TableItemOS tableOrdemItem;
    private TipoDeServicoService tipoServicoService;

    public FrmOrdemDeServico() {
        initComponents();
    }

    public FrmOrdemDeServico(JDesktopPane dsk) {
        initComponents();
        service = new OrdemDeServicoService();
        MetodosUteis.DefineFontTextField(this, "arial", Font.BOLD, 14);
        jLTotal2.setText(MetodosUteis.formataMoeda(0d));
        jPanelCliente.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelOS = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFones = new javax.swing.JTable();
        jBGerarOS = new javax.swing.JButton();
        jComboTipoDeServico = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jPanelItensOS = new javax.swing.JPanel();
        jTextPesquisaMaterial = new javax.swing.JTextField();
        jButtonConsultaMaterial = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableMaterial = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableItensOS = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jBFinalizarOS = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTAObservacoes = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLTotal2 = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jPanelPesquisa = new javax.swing.JPanel();
        jComboTipoPesquisaOS = new javax.swing.JComboBox();
        jTextPesquisaOS = new javax.swing.JTextField();
        jButtonPesquisarOS = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTablePesquisaOS = new javax.swing.JTable();
        jPanelCliente = new javax.swing.JPanel();
        jComboTipoPesquisaCliente = new javax.swing.JComboBox();
        jTextPesquisa = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePesquisaCliente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLNrOS = new javax.swing.JLabel();
        jLStatusOS = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Ordem de Serviço");
        setToolTipText("");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelOS.setVerifyInputWhenFocusTarget(false);
        jPanelOS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jrinstall/icon/novo-24.png"))); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jPanelOS.add(jButtonNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 620, -1, -1));

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jrinstall/icon/excluir-24.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanelOS.add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 620, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Cliente");
        jPanelOS.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, 120, -1));

        jTextNome.setEnabled(false);
        jPanelOS.add(jTextNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, 321, 30));

        jTableFones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableFones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFonesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableFonesMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFones);

        jPanelOS.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 230, 90));

        jBGerarOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jrinstall/icon/sinc-32.png"))); // NOI18N
        jBGerarOS.setText("Gerar OS");
        jBGerarOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGerarOSActionPerformed(evt);
            }
        });
        jPanelOS.add(jBGerarOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 130, 90));

        jComboTipoDeServico.setNextFocusableComponent(jBGerarOS);
        jComboTipoDeServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoDeServicoActionPerformed(evt);
            }
        });
        jPanelOS.add(jComboTipoDeServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 320, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Tipo de serviço");
        jPanelOS.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 90, -1));

        jPanelItensOS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelItensOS.setToolTipText("");
        jPanelItensOS.setName("Itens da OS"); // NOI18N
        jPanelItensOS.setOpaque(false);
        jPanelItensOS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextPesquisaMaterial.setEnabled(false);
        jPanelItensOS.add(jTextPesquisaMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 316, 30));

        jButtonConsultaMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jrinstall/icon/pesquisar-24.png"))); // NOI18N
        jButtonConsultaMaterial.setText("Pesquisar");
        jButtonConsultaMaterial.setEnabled(false);
        jButtonConsultaMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaMaterialActionPerformed(evt);
            }
        });
        jPanelItensOS.add(jButtonConsultaMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Observações");
        jPanelItensOS.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 120, -1));

        jTableMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableMaterial.setEnabled(false);
        jTableMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMaterialMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableMaterialMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(jTableMaterial);

        jPanelItensOS.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 73, 540, 167));

        jTableItensOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableItensOS.setEnabled(false);
        jTableItensOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableItensOSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableItensOSMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(jTableItensOS);

        jPanelItensOS.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 390, 416));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Itens ");
        jPanelItensOS.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 120, -1));

        jBFinalizarOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jrinstall/icon/finalizar-24.png"))); // NOI18N
        jBFinalizarOS.setText("Finalizar OS");
        jBFinalizarOS.setEnabled(false);
        jBFinalizarOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFinalizarOSActionPerformed(evt);
            }
        });
        jPanelItensOS.add(jBFinalizarOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        jTAObservacoes.setColumns(20);
        jTAObservacoes.setRows(5);
        jTAObservacoes.setEnabled(false);
        jTAObservacoes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTAObservacoesFocusLost(evt);
            }
        });
        jScrollPane5.setViewportView(jTAObservacoes);

        jPanelItensOS.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 540, 130));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Pesquisar Material");
        jPanelItensOS.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 9, 120, -1));

        jPanelOS.add(jPanelItensOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1050, 470));
        jPanelItensOS.getAccessibleContext().setAccessibleName("sss");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Telefones");
        jPanelOS.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 80, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Valor Total: ");
        jPanelOS.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, -1, -1));

        jLTotal2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLTotal2.setForeground(java.awt.Color.red);
        jLTotal2.setText("total");
        jPanelOS.add(jLTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 110, -1));

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jrinstall/icon/salvar-24.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanelOS.add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, -1, -1));

        jTabbedPane1.addTab("Ordem de Serviço", jPanelOS);

        jComboTipoPesquisaOS.addItem("OS");
        jComboTipoPesquisaOS.addItem("Em aberto");
        jComboTipoPesquisaOS.addItem("Finalizadas");
        jComboTipoPesquisaOS.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboTipoPesquisaOSItemStateChanged(evt);
            }
        });
        jComboTipoPesquisaOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoPesquisaOSActionPerformed(evt);
            }
        });

        jButtonPesquisarOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jrinstall/icon/pesquisar-24.png"))); // NOI18N
        jButtonPesquisarOS.setText("Pesquisar");
        jButtonPesquisarOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarOSActionPerformed(evt);
            }
        });

        jTablePesquisaOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTablePesquisaOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePesquisaOSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTablePesquisaOSMouseEntered(evt);
            }
        });
        jScrollPane6.setViewportView(jTablePesquisaOS);

        javax.swing.GroupLayout jPanelPesquisaLayout = new javax.swing.GroupLayout(jPanelPesquisa);
        jPanelPesquisa.setLayout(jPanelPesquisaLayout);
        jPanelPesquisaLayout.setHorizontalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                        .addComponent(jComboTipoPesquisaOS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextPesquisaOS, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 388, Short.MAX_VALUE)
                        .addComponent(jButtonPesquisarOS, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
        );
        jPanelPesquisaLayout.setVerticalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPesquisaOS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisarOS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboTipoPesquisaOS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pesquisa OS", jPanelPesquisa);

        jComboTipoPesquisaCliente.addItem("Nome");
        jComboTipoPesquisaCliente.addItem("CPF_CNPJ");
        jComboTipoPesquisaCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboTipoPesquisaClienteItemStateChanged(evt);
            }
        });
        jComboTipoPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoPesquisaClienteActionPerformed(evt);
            }
        });

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jrinstall/icon/pesquisar-24.png"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jTablePesquisaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTablePesquisaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePesquisaClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTablePesquisaClienteMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePesquisaCliente);

        javax.swing.GroupLayout jPanelClienteLayout = new javax.swing.GroupLayout(jPanelCliente);
        jPanelCliente.setLayout(jPanelClienteLayout);
        jPanelClienteLayout.setHorizontalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addComponent(jComboTipoPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 388, Short.MAX_VALUE)
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
        );
        jPanelClienteLayout.setVerticalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboTipoPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Clientes", jPanelCliente);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 1058, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Ordem de Serviço");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 21, -1, -1));

        jLNrOS.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLNrOS.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLNrOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(919, 11, 183, 30));

        jLStatusOS.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLStatusOS.setForeground(new java.awt.Color(255, 0, 0));
        jLStatusOS.setText(" ");
        getContentPane().add(jLStatusOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 11, 330, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboTipoPesquisaClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboTipoPesquisaClienteItemStateChanged
        // TODO add your handling code here:
        jTextPesquisa.setText(null);
    }//GEN-LAST:event_jComboTipoPesquisaClienteItemStateChanged

    private void jComboTipoPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoPesquisaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTipoPesquisaClienteActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        clienteService = new ClienteService();
        if (jTextPesquisa.getText().length() == 0) {
            MetodosUteis.showMsg("Informe o Item a pesquisar!");

        } else {
            lista = new ArrayList<Cliente>();
            String criterio = String.valueOf(jComboTipoPesquisaCliente.getSelectedItem().toString());
            mapPesquisa = new HashMap();

            if (criterio.equals("Nome")) {
                mapPesquisa.put("Nome", "SELECT distinct(c) FROM Cliente c left join fetch c.telefones WHERE c.nome like '" + jTextPesquisa.getText() + "%'");
            } else if (criterio.equals("CPF_CNPJ")) {
                mapPesquisa.put("CPF_CNPJ", "SELECT distinct(c) FROM Cliente c left join fetch c.telefones WHERE c.cpfCnpj = " + Integer.parseInt(jTextPesquisa.getText()));
            }

            lista = clienteService.getListByHQL((String) mapPesquisa.get(criterio));
            montaTabelaCliente(lista);

        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void montaTabelaCliente(List<Cliente> lista) {
        String colunas[] = new String[]{"Nome", "Endereco", "Cidade", "Bairro"};
        ArrayList linhas = new ArrayList<Cliente>();
        for (Cliente p : lista) {
            linhas.add(new String[]{p.getNome(), p.getEndereco(), p.getCidade().getDescricaoCidade(), p.getBairro().getDescricaoBairro()});
        }
        tableCliente = new TableCliente(linhas, colunas, lista);
        jTablePesquisaCliente.setModel(tableCliente);
        jTablePesquisaCliente.getColumnModel().getColumn(0).setHeaderValue("Cliente");
        jTablePesquisaCliente.getColumnModel().getColumn(0).setPreferredWidth(200);
        jTablePesquisaCliente.getColumnModel().getColumn(1).setHeaderValue("Endereco");
        jTablePesquisaCliente.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTablePesquisaCliente.getColumnModel().getColumn(2).setHeaderValue("Cidade");
        jTablePesquisaCliente.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTablePesquisaCliente.getColumnModel().getColumn(3).setHeaderValue("Bairro");
        jTablePesquisaCliente.getColumnModel().getColumn(3).setPreferredWidth(50);

    }

    private void jTablePesquisaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisaClienteMouseClicked

        ordemServico = new OrdemServico();
        ordemServico.setCliente(new Cliente());
        ordemServico.setCliente((Cliente) tableCliente.getcliente(jTablePesquisaCliente.getSelectedRow()));
        jTabbedPane1.setSelectedComponent(jPanelOS);
        preencheCamposComCliente(ordemServico.getCliente());
        clickTabelaCliente();
        MetodosUteis.HabilitarTextField(this);
        jTabbedPane1.setSelectedComponent(jPanelOS);
    }//GEN-LAST:event_jTablePesquisaClienteMouseClicked

    private void preencheCamposComOS() {
        try {
            preencheCamposComCliente(ordemServico.getCliente());
            montaTabelaItens(ordemServico.getOrdemServicoItemList());
            jTAObservacoes.setText(ordemServico.getObsOs());
            jLTotal2.setText(MetodosUteis.formataMoeda(ordemServico.getValorservico()));
            if (ordemServico.getFinalizado()) {
                jLStatusOS.setText("Finalizado em" + ordemServico.getDataExecucao());
            } else {
                jLStatusOS.setText("Ativo");
            }
            jComboTipoDeServico.setSelectedItem(ordemServico.getTipoServico());

        } catch (Exception ex) {
            MetodosUteis.showMsg("Erro ao carregar OS:" + ex.getMessage());
        } catch (Throwable ex) {
            MetodosUteis.showMsg("Erro ao carregar OS:" + ex.getMessage());
        }
    }

    private void clickTabelaCliente() {
        jButtonNovo.setEnabled(true);
        jButtonExcluir.setEnabled(true);

    }
    private void jTablePesquisaClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisaClienteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablePesquisaClienteMouseEntered

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        MetodosUteis.HabilitarTextField(this);
        MetodosUteis.LimparTextField(this);
       // cliente = new Cliente();
        // cliente.setUsuarioCadastro(usuarioLogado.getUsuario());
        //  cliente.setDataCadastro(new Date());

        //  clickNovo();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        /*       if (null == cliente.getIdCliente()) {
         MetodosUteis.showMsg("Seleciona um Cliente válido pra excluir.");
         } else {
         if (MetodosUteis.showQuestionMessage("Deseja excluir o Item selecionado?", "Atenção") == 0) {
         if (clienteService.delete(cliente)) {
         MetodosUteis.showMsg("Cliente excluído com sucesso!");
         MetodosUteis.LimparTextField(this);
         }
         }
         }
         */
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableFonesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFonesMouseClicked

    }//GEN-LAST:event_jTableFonesMouseClicked

    private void jTableFonesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFonesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableFonesMouseEntered

    private void estadoCamposOS(boolean acao) {
        jTextPesquisaMaterial.setEnabled(acao);
        jButtonConsultaMaterial.setEnabled(acao);
        jTableMaterial.setEnabled(acao);
        jTableItensOS.setEnabled(acao);
        jTAObservacoes.setEnabled(acao);
        jButtonSalvar.setEnabled(acao);

    }
    private void jBGerarOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGerarOSActionPerformed
        // TODO add your handling code here:    
        try {
            ordemServico.setDataCadastro(new Date());
            String idItem = jComboTipoDeServico.getSelectedItem().toString();
            ordemServico.setTipoServico(new TipoServico((Integer) getMapTipoServico().get(idItem)));
            ordemServico.setUsuarioCadastro(Principal.usuarioLogado.getUsuario());
            service.Save(ordemServico);
            ordemServico.setOrdemServicoItemList(new ArrayList<OrdemServicoItem>());
            jLNrOS.setText("OS: " + String.format("%04d", ordemServico.getIdOrdemServico()));
            estadoCamposOS(true);
        } catch (HibernateException e) {
            MetodosUteis.showMsg("Erro ao gerar OS:" + e.getMessage());
        }
    }//GEN-LAST:event_jBGerarOSActionPerformed


    private void jComboTipoDeServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoDeServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTipoDeServicoActionPerformed

    private void jButtonConsultaMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaMaterialActionPerformed
        if (jTextPesquisaMaterial.getText().length() == 0) {
            MetodosUteis.showMsg("Informe o Item a pesquisar!");

        } else {
            lista = new ArrayList<Material>();

            try {
                lista = service.getListByHQL((String) "SELECT m FROM Material m WHERE m.descricaomaterial like '" + jTextPesquisaMaterial.getText() + "%'");
                montaTabelaConsultaMaterial(lista);
            } catch (HibernateException e) {
                MetodosUteis.showMsg("Erro ao consulta Material: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonConsultaMaterialActionPerformed

    private void montaTabelaConsultaMaterial(List<Material> lista) {
        String colunas[] = new String[]{"Descrição Material", "Valor"};
        ArrayList linhas = new ArrayList<Material>();
        for (Material p : lista) {
            linhas.add(new String[]{p.getDescricaomaterial(), MetodosUteis.formataMoeda(p.getValorPadrao())});
        }
        tableMaterial = new TableMaterial(linhas, colunas, lista);
        tableMaterial.setPermiteEditarCelula(false);
        jTableMaterial.setModel(tableMaterial);
        jTableMaterial.getColumnModel().getColumn(0).setHeaderValue("Descrição");
        jTableMaterial.getColumnModel().getColumn(0).setPreferredWidth(200);
        jTableMaterial.getColumnModel().getColumn(1).setHeaderValue("Valor");
        jTableMaterial.getColumnModel().getColumn(1).setPreferredWidth(70);
    }
    private void jTableMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMaterialMouseClicked

        Material material = new Material();
        material = (Material) tableMaterial.getMaterial(jTableMaterial.getSelectedRow());
        ordemItem = new OrdemServicoItem();
        ordemItem.setMaterial(material);
        ordemItem.setOrdemServico(ordemServico);
        ordemItem.setValorUnitario(material.getValorPadrao());
        ordemItem.setQuantidade(1);
        ordemItem.setValorTotal(material.getValorPadrao());
        try {
            service.SaveItem(ordemItem);
            ordemServico.getOrdemServicoItemList().add(ordemItem);
            somaTotalServico();
        } catch (HibernateException e) {
            MetodosUteis.showMsg("Erro ao salvar item: " + e.getMessage());
        }
        montaTabelaItens(ordemServico.getOrdemServicoItemList());
    }//GEN-LAST:event_jTableMaterialMouseClicked

    private void montaTabelaItens(List<OrdemServicoItem> listaItens) {
        String colunas[] = new String[]{"Descrição Material", "Qt", "Valor", "Total", "X"};
        ArrayList linhas = new ArrayList<OrdemServicoItem>();
        for (OrdemServicoItem p : listaItens) {
            linhas.add(new String[]{p.getMaterial().getDescricaomaterial(), p.getQuantidade().toString(), MetodosUteis.formataMoeda(p.getValorUnitario()), MetodosUteis.formataMoeda(p.getValorTotal()), "X"});
        }
        tableOrdemItem = new TableItemOS(linhas, colunas, listaItens);
        jTableItensOS.setModel(tableOrdemItem);
        jTableItensOS.getColumnModel().getColumn(0).setHeaderValue("Descrição");
        jTableItensOS.getColumnModel().getColumn(0).setPreferredWidth(200);
        jTableItensOS.getColumnModel().getColumn(1).setHeaderValue("Qt");
        jTableItensOS.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTableItensOS.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(montaComboQuantidade()));
        jTableItensOS.getColumnModel().getColumn(2).setHeaderValue("Vl Un");
        jTableItensOS.getColumnModel().getColumn(2).setPreferredWidth(90);
        jTableItensOS.getColumnModel().getColumn(3).setHeaderValue("Vl Total");
        jTableItensOS.getColumnModel().getColumn(3).setPreferredWidth(90);
        jTableItensOS.getColumnModel().getColumn(4).setHeaderValue("X");
        jTableItensOS.getColumnModel().getColumn(4).setPreferredWidth(10);
    }

    private JComboBox montaComboQuantidade() {
        javax.swing.JComboBox cb = new JComboBox();
        for (int i = 1; i < 10; i++) {
            cb.addItem(i);
        }

        return cb;

    }
    private void jTableMaterialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMaterialMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableMaterialMouseEntered

    private void jTableItensOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableItensOSMouseClicked

        if (jTableItensOS.getSelectedColumn() == 4) {
            if (MetodosUteis.showQuestionMessage("Deseja Excluir o Item selecionado?", "Atenção") == 0) {
                service.delete(ordemServico.getOrdemServicoItemList().get(jTableItensOS.getSelectedRow()));
                ordemServico.getOrdemServicoItemList().remove(jTableItensOS.getSelectedRow());
                montaTabelaItens(ordemServico.getOrdemServicoItemList());
            }
        }

        somaTotalServico();
    }//GEN-LAST:event_jTableItensOSMouseClicked

    private void somaTotalServico() {
        double total = 0d;

        for (OrdemServicoItem item : ordemServico.getOrdemServicoItemList()) {
            total += item.getValorTotal();
        }
        ordemServico.setValorservico(total);
        jLTotal2.setText(MetodosUteis.formataMoeda(ordemServico.getValorservico()));

    }
    private void jTableItensOSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableItensOSMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableItensOSMouseEntered

    private void jBFinalizarOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFinalizarOSActionPerformed

        if (ordemServico.getValorservico() > 0) {
            if (MetodosUteis.showQuestionMessage("Deseja Finalizar esta OS?", "Atenção") == 0) {
                ordemServico.setFinalizado(true);
                ordemServico.setDataExecucao(MetodosUteis.getDataManipulada(0));
                service.Save(ordemServico);

            }
        } else {
            MetodosUteis.showMsg("Não é permitido finalizar OS sem itens.");
        }
    }//GEN-LAST:event_jBFinalizarOSActionPerformed

    private void jTAObservacoesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTAObservacoesFocusLost
        if (!jTAObservacoes.getText().isEmpty()) {
            ordemServico.setObsOs(jTAObservacoes.getText());
            service.Save(ordemServico);
        }
    }//GEN-LAST:event_jTAObservacoesFocusLost

    private void jComboTipoPesquisaOSItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboTipoPesquisaOSItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTipoPesquisaOSItemStateChanged

    private void jComboTipoPesquisaOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoPesquisaOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTipoPesquisaOSActionPerformed

    private void jButtonPesquisarOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarOSActionPerformed
        lista = new ArrayList<OrdemServico>();
        String criterio = String.valueOf(jComboTipoPesquisaOS.getSelectedItem().toString());
        mapPesquisa = new HashMap();

        if (criterio.equalsIgnoreCase("Em aberto")) {
            mapPesquisa.put("Em aberto", "SELECT distinct(o) FROM OrdemServico o join fetch o.cliente c join fetch c.telefones WHERE o.finalizado = 0 order by o.idOrdemServico ");
        } else if (criterio.equals("Finalizadas")) {
            mapPesquisa.put("Finalizadas", "SELECT o FROM OrdemServico o join fetch o.cliente c join fetch c.telefones WHERE o.finalizado = 0");
        } else if (criterio.equals("OS")) {
            if (jTextPesquisaOS.getText().length() != 0) {
                mapPesquisa.put("OS", "SELECT o FROM OrdemServico o join fetch o.cliente c join fetch c.telefones WHERE o.idOrdemServico = " + jTextPesquisaOS.getText());
            } else {
                MetodosUteis.showMsg("Informe o Número da Ordem de serviço.");
            }
        }

        lista = service.getListByHQL((String) mapPesquisa.get(criterio));
        montaTabelaOS(lista);
    }//GEN-LAST:event_jButtonPesquisarOSActionPerformed

    private void montaTabelaOS(List<OrdemServico> lista) {
        if (lista.size() == 0) {
            MetodosUteis.showMsg("Não há itens para listagem");
        } else {
            String colunas[] = new String[]{"OS", "Cliente", "Tipo de Serviço", "Data Cadastro"};
            ArrayList linhas = new ArrayList<Cliente>();
            for (OrdemServico os : lista) {
                linhas.add(new String[]{os.getIdOrdemServico().toString(), os.getCliente().getNome(), os.getTipoServico().getDescricaoTipoServico(), os.getDataCadastro().toString()});
            }

            tableOrdemServico = new TableOrdemServico(linhas, colunas, lista);
            jTablePesquisaOS.setModel(tableOrdemServico);
            jTablePesquisaOS.getColumnModel().getColumn(0).setHeaderValue("OS");
            jTablePesquisaOS.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTablePesquisaOS.getColumnModel().getColumn(1).setHeaderValue("Cliente");
            jTablePesquisaOS.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTablePesquisaOS.getColumnModel().getColumn(2).setHeaderValue("Tipo de Serviço");
            jTablePesquisaOS.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTablePesquisaOS.getColumnModel().getColumn(3).setHeaderValue("Data Cadastro");
            jTablePesquisaOS.getColumnModel().getColumn(3).setPreferredWidth(50);
        }
    }


    private void jTablePesquisaOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisaOSMouseClicked
        ordemServico = new OrdemServico();
        ordemServico = (OrdemServico) tableOrdemServico.getOrdemServico(jTablePesquisaOS.getSelectedRow());
        preencheCamposComOS();
        MetodosUteis.HabilitarTextField(this);
        jTabbedPane1.setSelectedComponent(jPanelOS);
        clickJTableSelecionaOS();
        estadoCamposOS(true);
        jBGerarOS.setEnabled(false);
        jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jTablePesquisaOSMouseClicked

    private void clickJTableSelecionaOS() {

    }

    private void jTablePesquisaOSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisaOSMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablePesquisaOSMouseEntered

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        try{
            service.Save(ordemServico);
        }catch (HibernateException ex){
            MetodosUteis.showMsg("Erro ao salvar OS. " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void preencheComboTipoServico() {
        tipoServicoService = new TipoDeServicoService();
        List<TipoServico> lista = new ArrayList<TipoServico>();
        lista = (List) tipoServicoService.getListByHQL("SELECT t FROM TipoServico t");
        jComboTipoDeServico.removeAllItems();
        mapTipoServico = new HashMap();
        for (TipoServico tp : lista) {
            mapTipoServico.put(tp.getDescricaoTipoServico(), tp.getIdTipoServico());
            jComboTipoDeServico.addItem(tp);
            // jComboTipoDeServico.setSelectedItem(ordemServico.getIdOrdemServico());
        }
    }

    public void montaTabelaFones(List<ClienteTelefone> lista) {
        try {
            if (lista != null) {
                String colunas[] = new String[]{"Telefone", "Tipo"};
                ArrayList linhas = new ArrayList<ClienteTelefone>();
                for (ClienteTelefone p : lista) {
                    linhas.add(new String[]{p.getNumero(), p.getOperadora().getDescricaoOperadora()});
                }
                setTabelaTelefone(new TableTelefone(linhas, colunas, lista));
//            tabelaTelefone.setOperadoras(operadoras);
                //          tabelaTelefone.setCliente(cliente);
                //        tabelaTelefone.setFrmCliente(this);
                jTableFones.setModel(getTabelaTelefone());
                jTableFones.getColumnModel().getColumn(0).setHeaderValue("Telefone");
                jTableFones.getColumnModel().getColumn(0).setPreferredWidth(120);
                jTableFones.getColumnModel().getColumn(1).setHeaderValue("Tipo");
                jTableFones.getColumnModel().getColumn(1).setPreferredWidth(60);

            }
        } catch (Exception ex) {
            MetodosUteis.showMsg("Erro ao criar tabela de telefones: " + ex.getMessage());
        }
    }

    public TableTelefone getTabelaTelefone() {
        return tabelaTelefone;
    }

    public void setTabelaTelefone(TableTelefone tabelaTelefone) {
        this.tabelaTelefone = tabelaTelefone;
    }

    public Map getMapTipoServico() {
        return mapTipoServico;
    }

    public void setMapTipoServico(Map mapTipoServico) {
        this.mapTipoServico = mapTipoServico;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBFinalizarOS;
    private javax.swing.JButton jBGerarOS;
    private javax.swing.JButton jButtonConsultaMaterial;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPesquisarOS;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboTipoDeServico;
    private javax.swing.JComboBox jComboTipoPesquisaCliente;
    private javax.swing.JComboBox jComboTipoPesquisaOS;
    private javax.swing.JLabel jLNrOS;
    private javax.swing.JLabel jLStatusOS;
    private javax.swing.JLabel jLTotal2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JPanel jPanelItensOS;
    private javax.swing.JPanel jPanelOS;
    private javax.swing.JPanel jPanelPesquisa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTAObservacoes;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableFones;
    private javax.swing.JTable jTableItensOS;
    private javax.swing.JTable jTableMaterial;
    private javax.swing.JTable jTablePesquisaCliente;
    private javax.swing.JTable jTablePesquisaOS;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextPesquisa;
    private javax.swing.JTextField jTextPesquisaMaterial;
    private javax.swing.JTextField jTextPesquisaOS;
    // End of variables declaration//GEN-END:variables

    private void preencheCamposComCliente(Cliente cliente) {
        preencheComboTipoServico();
        jTextNome.setText(cliente.getNome());
        montaTabelaFones(cliente.getTelefones());
    }
}
